const Parse = require("parse/node");
const yaml = require("js-yaml");
const fs = require("fs");
const path = require("path");

const mapParseTypeToOpenAPI = (parseType) => {
  // Normalisasi input ke string agar aman
  const typeStr = String(parseType);

  const mapping = {
    String: { type: "string" },
    Number: { type: "number" },
    Boolean: { type: "boolean" },
    Date: { type: "string", format: "date-time" },
    Object: { type: "object" },
    Array: { type: "array", items: { type: "string" } }, // Generic array
    File: { type: "string", format: "binary" },
    Pointer: { type: "string", description: "Pointer ID to another class" },
    Relation: {
      type: "array",
      items: { type: "object" },
      description: "Relation to other objects",
    },
    GeoPoint: {
      type: "object",
      properties: {
        latitude: { type: "number" },
        longitude: { type: "number" },
      },
    },
    Polygon: { type: "object" },
    Bytes: { type: "string", format: "byte" },
  };

  return (
    mapping[typeStr] || {
      type: "string",
      description: `Unknown type: ${typeStr}`,
    }
  );
};

class SwaggerGenerator {
  constructor(config) {
    // Input validation to ensure user data security
    if (!config.appId || !config.masterKey || !config.serverUrl) {
      throw new Error(
        "Missing required Parse configuration: appId, masterKey, or serverUrl."
      );
    }

    this.config = config;
    this.outputPath = config.outputPath || "./parse-swagger.yaml";

    // Initialize a specific Parse instance for this generator.
    // It is safe because it runs in memory at user runtime.
    Parse.initialize(config.appId, null, config.masterKey);
    Parse.serverURL = config.serverUrl;
  }

  async generate() {
    console.log(`🔍 Connecting to Parse Server at ${this.config.serverUrl}...`);

    try {
      const schemas = await Parse.Schema.all();

      const swaggerDoc = {
        openapi: "3.0.0",
        info: {
          title: this.config.apiTitle || "Parse Server API",
          version: this.config.apiVersion || "1.0.0",
          description: "Generated by parse-server-swagger-generator",
        },
        servers: [{ url: this.config.serverUrl }],
        components: {
          securitySchemes: {
            AppId: {
              type: "apiKey",
              in: "header",
              name: "X-Parse-Application-Id",
            },
            SessionToken: {
              type: "apiKey",
              in: "header",
              name: "X-Parse-Session-Token",
            },
          },
          schemas: {},
        },
        security: [{ AppId: [] }],
        paths: {},
      };

      schemas.forEach((schema) => {
        const className = schema.className;
        // Option to exclude system classes
        if (
          this.config.excludeSystemClasses &&
          className.startsWith("_") &&
          className !== "_User"
        )
          return;

        // --- The logic of generating Schema & Path is the same as before ---
        // (Shortened for code brevity, property mapping logic is here)
        // ...
        // A. Bangun Component Schema (Model)
        const properties = {
          objectId: { type: "string" },
          createdAt: { type: "string", format: "date-time" },
          updatedAt: { type: "string", format: "date-time" },
        };

        Object.keys(schema.fields).forEach((field) => {
          properties[field] = mapParseTypeToOpenAPI(schema.fields[field].type);
        });

        // Example placeholder for valid code
        swaggerDoc.components.schemas[className] = {
          type: "object",
          properties: {},
        };

        // B. Bangun Paths (CRUD Operations)
        const path = `/classes/${className}`;
        const pathById = `/classes/${className}/{objectId}`;

        swaggerDoc.paths[path] = {
          get: {
            tags: [className],
            summary: `Get list of ${className}`,
            parameters: [
              {
                name: "where",
                in: "query",
                schema: { type: "string" },
                description: "JSON encoded query",
              },
              { name: "limit", in: "query", schema: { type: "integer" } },
              { name: "skip", in: "query", schema: { type: "integer" } },
            ],
            responses: {
              200: {
                description: "Successful response",
                content: {
                  "application/json": {
                    schema: {
                      type: "object",
                      properties: {
                        results: {
                          type: "array",
                          items: { $ref: `#/components/schemas/${className}` },
                        },
                      },
                    },
                  },
                },
              },
            },
          },
          // POST (Create)
          post: {
            tags: [className],
            summary: `Create ${className}`,
            requestBody: {
              content: {
                "application/json": {
                  schema: { $ref: `#/components/schemas/${className}` },
                },
              },
            },
            responses: { 201: { description: "Created" } },
          },
        };

        // GET (By ID), PUT, DELETE
        swaggerDoc.paths[pathById] = {
          get: {
            tags: [className],
            summary: `Get ${className} by ID`,
            parameters: [
              {
                name: "objectId",
                in: "path",
                required: true,
                schema: { type: "string" },
              },
            ],
            responses: { 200: { description: "Success" } },
          },
          put: {
            tags: [className],
            summary: `Update ${className}`,
            parameters: [
              {
                name: "objectId",
                in: "path",
                required: true,
                schema: { type: "string" },
              },
            ],
            requestBody: {
              content: {
                "application/json": {
                  schema: { $ref: `#/components/schemas/${className}` },
                },
              },
            },
            responses: { 200: { description: "Updated" } },
          },
          delete: {
            tags: [className],
            summary: `Delete ${className}`,
            parameters: [
              {
                name: "objectId",
                in: "path",
                required: true,
                schema: { type: "string" },
              },
            ],
            responses: { 200: { description: "Deleted" } },
          },
        };
      });

      const yamlStr = yaml.dump(swaggerDoc);

      // Pastikan direktori ada
      const dir = path.dirname(this.outputPath);
      if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
      }

      fs.writeFileSync(this.outputPath, yamlStr, "utf8");
      console.log(`✅ Swagger file generated at: ${this.outputPath}`);

      return swaggerDoc; // Return object juga untuk penggunaan programmatic
    } catch (error) {
      console.error("❌ Error generating swagger:", error.message);
      throw error;
    }
  }
}

module.exports = SwaggerGenerator;
