const Parse = require("parse/node");
const yaml = require("js-yaml");
const fs = require("fs");
const path = require("path");

class SwaggerGenerator {
  constructor(config) {
    // Input validation to ensure user data security
    if (!config.appId || !config.masterKey || !config.serverUrl) {
      throw new Error(
        "Missing required Parse configuration: appId, masterKey, or serverUrl."
      );
    }

    this.config = config;
    this.outputPath = config.outputPath || "./parse-swagger.yaml";

    // Initialize a specific Parse instance for this generator.
    // It is safe because it runs in memory at user runtime.
    Parse.initialize(config.appId, null, config.masterKey);
    Parse.serverURL = config.serverUrl;
  }

  async generate() {
    console.log(`🔍 Connecting to Parse Server at ${this.config.serverUrl}...`);

    try {
      const schemas = await Parse.Schema.all();

      const swaggerDoc = {
        openapi: "3.0.0",
        info: {
          title: this.config.apiTitle || "Parse Server API",
          version: this.config.apiVersion || "1.0.0",
          description: "Generated by parse-server-swagger-generator",
        },
        servers: [{ url: this.config.serverUrl }],
        components: {
          securitySchemes: {
            AppId: {
              type: "apiKey",
              in: "header",
              name: "X-Parse-Application-Id",
            },
            SessionToken: {
              type: "apiKey",
              in: "header",
              name: "X-Parse-Session-Token",
            },
          },
          schemas: {},
        },
        security: [{ AppId: [] }],
        paths: {},
      };

      schemas.forEach((schema) => {
        const className = schema.className;
        // Option to exclude system classes
        if (
          this.config.excludeSystemClasses &&
          className.startsWith("_") &&
          className !== "_User"
        )
          return;

        // --- The logic of generating Schema & Path is the same as before ---
        // (Shortened for code brevity, property mapping logic is here)
        // ...

        // Example placeholder for valid code
        swaggerDoc.components.schemas[className] = {
          type: "object",
          properties: {},
        };
      });

      const yamlStr = yaml.dump(swaggerDoc);

      // Pastikan direktori ada
      const dir = path.dirname(this.outputPath);
      if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
      }

      fs.writeFileSync(this.outputPath, yamlStr, "utf8");
      console.log(`✅ Swagger file generated at: ${this.outputPath}`);

      return swaggerDoc; // Return object juga untuk penggunaan programmatic
    } catch (error) {
      console.error("❌ Error generating swagger:", error.message);
      throw error;
    }
  }
}

module.exports = SwaggerGenerator;
